"""CID Editorial Intelligence Transcript Provenance package."""

from scripts.editorial_intelligence.transcript_provenance.transcript_segment import (
    PHASE,
    SOURCE_TIMECODE_STATUS_ABSENT,
    SOURCE_TIMECODE_STATUS_UNAVAILABLE,
    SOURCE_TIMECODE_STATUS_UNSUPPORTED,
    SOURCE_RELATIVE_VERIFY_TOLERANCE_SECONDS,
    SEGMENT_END_FRAME_ROUNDING_POLICY,
    SEGMENT_START_FRAME_ROUNDING_POLICY,
    ERROR_CODE_INVALID_INPUT,
    ERROR_CODE_INVALID_SEGMENT,
    ERROR_CODE_SEGMENTS_NOT_MONOTONIC,
    TranscriptSegment,
    TranscriptSegmentError,
    build_editorial_citation,
    build_source_timecode,
    classify_timecode_format,
    derive_ndf_timecode,
    format_ndf_timecode,
    nominal_frames_per_second,
    parse_ndf_timecode,
    seconds_to_end_frame,
    seconds_to_start_frame,
    timecode_to_frames,
    transcription_result_to_transcript_segments,
)

__all__ = [
    "PHASE",
    "SOURCE_TIMECODE_STATUS_ABSENT",
    "SOURCE_TIMECODE_STATUS_UNAVAILABLE",
    "SOURCE_TIMECODE_STATUS_UNSUPPORTED",
    "SOURCE_RELATIVE_VERIFY_TOLERANCE_SECONDS",
    "SEGMENT_END_FRAME_ROUNDING_POLICY",
    "SEGMENT_START_FRAME_ROUNDING_POLICY",
    "ERROR_CODE_INVALID_INPUT",
    "ERROR_CODE_INVALID_SEGMENT",
    "ERROR_CODE_SEGMENTS_NOT_MONOTONIC",
    "TranscriptSegment",
    "TranscriptSegmentError",
    "build_editorial_citation",
    "build_source_timecode",
    "classify_timecode_format",
    "derive_ndf_timecode",
    "format_ndf_timecode",
    "nominal_frames_per_second",
    "parse_ndf_timecode",
    "seconds_to_end_frame",
    "seconds_to_start_frame",
    "timecode_to_frames",
    "transcription_result_to_transcript_segments",
]
