"""CID Editorial Intelligence Audio Extraction package."""

from scripts.editorial_intelligence.audio_extraction.audio_extraction import (
    AUDIO_EXTRACTION_TIMEOUT_ABSOLUTE_MAX_SECONDS,
    AUDIO_EXTRACTION_TIMEOUT_FIXED_OVERHEAD_SECONDS,
    AUDIO_EXTRACTION_TIMEOUT_FACTOR,
    AUDIO_EXTRACTION_TIMEOUT_MIN_SECONDS,
    AUDIO_STREAM_SELECTION_POLICY,
    TRANSCRIPTION_AUDIO_CANONICAL_FORMAT,
    TRANSCRIPTION_AUDIO_CHANNEL_COUNT,
    TRANSCRIPTION_AUDIO_SAMPLE_FORMAT,
    TRANSCRIPTION_AUDIO_SAMPLE_RATE,
    ExtractedAudioResult,
    extract_audio,
    resolve_ffmpeg_path,
)

__all__ = [
    "AUDIO_EXTRACTION_TIMEOUT_ABSOLUTE_MAX_SECONDS",
    "AUDIO_EXTRACTION_TIMEOUT_FIXED_OVERHEAD_SECONDS",
    "AUDIO_EXTRACTION_TIMEOUT_FACTOR",
    "AUDIO_EXTRACTION_TIMEOUT_MIN_SECONDS",
    "AUDIO_STREAM_SELECTION_POLICY",
    "TRANSCRIPTION_AUDIO_CANONICAL_FORMAT",
    "TRANSCRIPTION_AUDIO_CHANNEL_COUNT",
    "TRANSCRIPTION_AUDIO_SAMPLE_FORMAT",
    "TRANSCRIPTION_AUDIO_SAMPLE_RATE",
    "ExtractedAudioResult",
    "extract_audio",
    "resolve_ffmpeg_path",
]
