"""add matcher jobs table and matcher_job_id to project_funding_matches

Revision ID: 6ba14a0d02b6
Revises: 20260423_000008
Create Date: 2026-04-23 13:34:58.444794

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba14a0d02b6'
down_revision = '20260423_000008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matcher_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_ref_id', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matcher_jobs_organization_id'), 'matcher_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_matcher_jobs_project_id'), 'matcher_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_matcher_jobs_status'), 'matcher_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_matcher_jobs_trigger_type'), 'matcher_jobs', ['trigger_type'], unique=False)
    op.create_index('ix_matcher_jobs_input_hash', 'matcher_jobs', ['input_hash'], unique=False)
    # Unique constraint to prevent duplicate jobs for same input within project/organization/trigger type
    op.create_unique_constraint('uq_matcher_jobs_project_organization_input_trigger', 'matcher_jobs', ['project_id', 'organization_id', 'input_hash', 'trigger_type'])

    # Add matcher_job_id to project_funding_matches
    op.add_column('project_funding_matches', sa.Column('matcher_job_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_funding_matches_matcher_job_id'), 'project_funding_matches', ['matcher_job_id'], unique=False)
    op.create_foreign_key(None, 'project_funding_matches', 'matcher_jobs', ['matcher_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_funding_matches', type_='foreignkey')
    op.drop_index(op.f('ix_project_funding_matches_matcher_job_id'), table_name='project_funding_matches')
    op.drop_column('project_funding_matches', 'matcher_job_id')
    op.drop_constraint('uq_matcher_jobs_project_organization_input_trigger', 'matcher_jobs', type_='unique')
    op.drop_index('ix_matcher_jobs_input_hash', table_name='matcher_jobs')
    op.drop_index(op.f('ix_matcher_jobs_trigger_type'), table_name='matcher_jobs')
    op.drop_index(op.f('ix_matcher_jobs_status'), table_name='matcher_jobs')
    op.drop_index(op.f('ix_matcher_jobs_project_id'), table_name='matcher_jobs')
    op.drop_index(op.f('ix_matcher_jobs_organization_id'), table_name='matcher_jobs')
    op.drop_table('matcher_jobs')
    # ### end Alembic commands ###