"""add storyboard_shots shot_number column

Revision ID: 7c72fdc1a074
Revises: c533c8d75a43
Create Date: 2026-05-30 21:14:25.477397
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '7c72fdc1a074'
down_revision = 'c533c8d75a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboard_shots', sa.Column('shot_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storyboard_shots', 'shot_number')
    # ### end Alembic commands ###
