#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MEDIA_DIR = ROOT / "src_frontend" / "public" / "landing-media"
COMPONENTS_DIR = ROOT / "src_frontend" / "src" / "components" / "landing"
DATA_DIR = ROOT / "src_frontend" / "src" / "data"
UTILS_DIR = ROOT / "src_frontend" / "src" / "utils"

BACKUP_MANIFEST_PATH = ROOT / ".tmp" / "landing_comfyui_v4" / "review" / "_landing_v4_backup_manifest.txt"
ROLLBACK_SCRIPT_PATH = ROOT / "scripts" / "rollback_landing_v4.sh"

V3_TO_V4_MAP: dict[str, str] = {
    "landing-hero-main-v3.webp": "landing-hero-main-v4.webp",
    "landing-problem-fragmented-v3.webp": "landing-problem-fragmented-v4.webp",
    "landing-ai-reasoning-v3.webp": "landing-ai-reasoning-v4.webp",
    "landing-concept-keyvisual-v3.webp": "landing-concept-keyvisual-v4.webp",
    "landing-storyboard-preview-v3.webp": "landing-storyboard-preview-v4.webp",
    "landing-comfyui-generation-v3.webp": "landing-comfyui-generation-v4.webp",
    "landing-cid-orchestration-v3.webp": "landing-cid-orchestration-v4.webp",
    "landing-producers-studios-v3.webp": "landing-producers-studios-v4.webp",
    "landing-professional-differential-v3.webp": "landing-professional-differential-v4.webp",
    "landing-delivery-final-v3.webp": "landing-delivery-final-v4.webp",
}

V4_IMAGES = list(V3_TO_V4_MAP.values())


def update_file_string(path: Path, replacements: list[tuple[str, str]]) -> bool:
    if not path.exists():
        print(f"  SKIP (not found): {path.relative_to(ROOT)}")
        return False
    source = path.read_text(encoding="utf-8")
    updated = source
    for before, after in replacements:
        if before in updated:
            updated = updated.replace(before, after)
    if updated != source:
        path.write_text(updated, encoding="utf-8")
        print(f"  UPDATED: {path.relative_to(ROOT)}")
        return True
    print(f"  NO CHANGES: {path.relative_to(ROOT)}")
    return False


def create_backup_manifest() -> None:
    BACKUP_MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    for v3_name in V3_TO_V4_MAP:
        v3_path = MEDIA_DIR / v3_name
        if v3_path.exists():
            lines.append(f"{v3_name}\texists")
        else:
            lines.append(f"{v3_name}\tmissing")
    BACKUP_MANIFEST_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Backup manifest: {BACKUP_MANIFEST_PATH.relative_to(ROOT)}")


def create_rollback_script() -> None:
    script = """#!/usr/bin/env bash
# Rollback V4 references to V3
# Generated by apply_landing_v4_references.py

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== Rollback V4 -> V3 ==="

"""
    for v3_name, v4_name in V3_TO_V4_MAP.items():
        script += f'echo "  Reverting {v4_name} -> {v3_name}"\n'
        script += f'sed -i "s|{v4_name}|{v3_name}|g" "$ROOT/src_frontend/src/components/landing/"*.tsx\n'
        script += f'sed -i "s|{v4_name}|{v3_name}|g" "$ROOT/src_frontend/src/data/landingVisualBible.ts"\n'

    script += '\necho "Rollback complete. Run `npm run build` to rebuild."\n'
    ROLLBACK_SCRIPT_PATH.write_text(script, encoding="utf-8")
    ROLLBACK_SCRIPT_PATH.chmod(0o755)
    print(f"Rollback script: {ROLLBACK_SCRIPT_PATH.relative_to(ROOT)}")


def main() -> int:
    print("=== V4 Reference Application ===")
    print()

    create_backup_manifest()

    components = list(COMPONENTS_DIR.glob("*.tsx"))
    data_files = list(DATA_DIR.glob("*.ts"))
    utils_files = list(UTILS_DIR.glob("*.ts"))

    replacements = [(v3_name, v4_name) for v3_name, v4_name in V3_TO_V4_MAP.items()]

    print("Updating components...")
    for path in components:
        update_file_string(path, replacements)

    print("Updating data files...")
    for path in data_files:
        update_file_string(path, replacements)

    print("Updating utils files...")
    for path in utils_files:
        update_file_string(path, replacements)

    create_rollback_script()

    print()
    print(f"V4 references applied. {len(V4_IMAGES)} files mapped.")
    print(f"V3 files preserved. Rollback available via: {ROLLBACK_SCRIPT_PATH.relative_to(ROOT)}")
    print("Run `npm run build` to rebuild frontend.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
