from pathlib import Path


DOC = Path("docs/product/local_media_agent/cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_fixture_v1.md")
TEMPLATE_QA_GATE_DOC = Path("docs/product/local_media_agent/cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_template_qa_gate_v1.md")
STATIC_TEMPLATE_DOC = Path("docs/product/local_media_agent/cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_template_v1.md")


def _text(path: Path = DOC) -> str:
    return path.read_text(encoding="utf-8")


def test_fixture_doc_exists_and_sources_exist() -> None:
    assert DOC.exists()
    assert TEMPLATE_QA_GATE_DOC.exists()
    assert STATIC_TEMPLATE_DOC.exists()


def test_phase_source_result_head_and_tag_are_recorded() -> None:
    text = _text()
    assert "CID.LOCAL_MEDIA_AGENT.REAL.PREFLIGHT.MINIMAL.RUNTIME.CLI.REAL_FOLDER.DEMO.VISIBLE.REPORT.STATIC.FIXTURE.V1" in text
    assert "CID.LOCAL_MEDIA_AGENT.REAL.PREFLIGHT.MINIMAL.RUNTIME.CLI.REAL_FOLDER.DEMO.VISIBLE.REPORT.STATIC.TEMPLATE.QA.GATE.V1" in text
    assert "LOCAL_MEDIA_AGENT_VISIBLE_REPORT_STATIC_TEMPLATE_QA_GATE_PASS_READY_FOR_STATIC_REPORT_FIXTURE" in text
    assert "507802177898bb83c122faa8086be8f51355dcef" in text
    assert "cid-dev-stable-local-media-agent-real-preflight-minimal-runtime-cli-real-folder-demo-visible-report-static-template-qa-gate-v1-20260620" in text


def test_fixture_identity_is_complete() -> None:
    text = _text()
    for token in [
        "CID Local Media Agent - Internal Demo Visible Report",
        "local_media_agent_visible_report_static_fixture_v1",
        "producer_product_post_internal_review",
        "internal_demo_only",
        "local_only",
        "approved_synthetic_controlled_demo",
        "Generated by runtime: `false`",
        "Runtime generator available: `false`",
        "Real client media used: `false`",
    ]:
        assert token in text


def test_required_visible_report_sections_are_present_and_ordered() -> None:
    text = _text()
    sections = [
        "## 1. Executive Summary",
        "## 2. Local-Only Privacy Confirmation",
        "## 3. Controlled Demo Input Summary",
        "## 4. Scanner Result Summary",
        "## 5. Accepted Media",
        "## 6. Rejected Non-Media",
        "## 7. Human Review Required",
        "## 8. Warnings",
        "## 9. Created Output Artifacts",
        "## 10. Roadmap Modules Not Yet Generated",
        "## 11. Producer Interpretation",
        "## 12. Next Technical Actions",
    ]
    positions = [text.index(section) for section in sections]
    assert positions == sorted(positions)


def test_privacy_confirmation_is_local_only_and_safe() -> None:
    text = _text()
    for token in [
        "Privacy status: `local_only_confirmed`",
        "Original media left client system: `false`",
        "SaaS upload performed: `false`",
        "Network call performed: `false`",
        "Database write performed: `false`",
        "avoids local user names, machine names, absolute system paths, repository paths, and real client material",
        "Input material type: `synthetic_placeholders_only`",
        "Input folder disclosure: `redacted_for_visible_report`",
        "Real shoot names disclosed: `false`",
        "Private project names disclosed: `false`",
    ]:
        assert token in text


def test_scanner_summary_matches_controlled_demo_numbers() -> None:
    text = _text()
    for token in [
        "Scanner status: `completed_with_warnings`",
        "Candidate media count: `5`",
        "Accepted media count: `4`",
        "Rejected non-media count: `3`",
        "Human review required count: `1`",
        "Warnings count: `1`",
        "ffprobe preflight: `skipped`",
    ]:
        assert token in text


def test_accepted_and_rejected_media_tables_are_present() -> None:
    text = _text()
    for token in [
        "| `.mov` | 1 | Candidate video media |",
        "| `.mp4` | 2 | Candidate video media |",
        "| `.wav` | 1 | Candidate production audio |",
        "| `.exe` | 1 | Rejected unsafe/non-media file |",
        "| `.txt` | 2 | Rejected text/non-media file |",
        "Accepted media are scanner candidates, not synchronized clips, transcribed clips, subtitled clips, edited deliverables, or exported timelines.",
        "Rejected non-media protects the media catalog from unrelated or unsafe files.",
    ]:
        assert token in text


def test_human_review_and_warning_are_visible() -> None:
    text = _text()
    for token in [
        "Human review required: `true`",
        "Human review reason: `unknown synthetic placeholder`",
        "Ambiguous material is surfaced to human review rather than silently accepted as production-ready media.",
        "Warning count: `1`",
        "Warning detail: `unknown synthetic placeholder`",
        "Warning severity: `controlled_demo_warning`",
        "The warning is acceptable for this controlled synthetic demo and must remain visible in the report.",
    ]:
        assert token in text


def test_current_outputs_and_roadmap_modules_are_not_overclaimed() -> None:
    text = _text()
    for token in [
        "`00_project/`",
        "`01_media_catalog/`",
        "`99_logs/`",
        "No audio synchronization outputs are generated in this fixture.",
        "No transcription outputs are generated in this fixture.",
        "No subtitle outputs are generated in this fixture.",
        "No export outputs are generated in this fixture.",
        "audio synchronization",
        "transcription",
        "subtitle generation",
        "translation",
        "report generation runtime",
        "DaVinci Resolve export",
        "Avid export",
        "`02_audio_sync/`",
        "`03_transcription/`",
        "`04_subtitles/`",
        "`05_reports/`",
        "`06_exports/`",
    ]:
        assert token in text


def test_fixture_does_not_contain_local_environment_leaks() -> None:
    text = _text()
    forbidden = [
        "/mnt/",
        "DESKTOP-",
        "harliesound",
        "SERVICIOS_CINE",
        "\\\\wsl.localhost",
        "C:\\\\",
    ]
    for token in forbidden:
        assert token not in text


def test_boundary_result_and_next_phase_are_recorded() -> None:
    text = _text()
    for token in [
        "runtime report generation",
        "scanner implementation changes",
        "real media scanning",
        "public demo use",
        "client-facing demo use",
        "ffprobe execution",
        "ffmpeg execution",
        "SaaS upload",
        "database writes",
        "network calls",
        "Docker or Alembic changes",
        "frontend/backend SaaS changes",
        "Stripe, AI Jobs, credits, or ledger changes",
        "LOCAL_MEDIA_AGENT_VISIBLE_REPORT_STATIC_FIXTURE_PASS_READY_FOR_STATIC_FIXTURE_QA_GATE",
        "CID.LOCAL_MEDIA_AGENT.REAL.PREFLIGHT.MINIMAL.RUNTIME.CLI.REAL_FOLDER.DEMO.VISIBLE.REPORT.STATIC.FIXTURE.QA.GATE.V1",
    ]:
        assert token in text
