from pathlib import Path


DOC = Path("docs/product/local_media_agent/cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_fixture_qa_gate_v1.md")
STATIC_FIXTURE_DOC = Path("docs/product/local_media_agent/cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_fixture_v1.md")
TEMPLATE_QA_GATE_DOC = Path("docs/product/local_media_agent/cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_template_qa_gate_v1.md")


def _text(path: Path = DOC) -> str:
    return path.read_text(encoding="utf-8")


def test_qa_gate_doc_exists_and_source_docs_exist() -> None:
    assert DOC.exists()
    assert STATIC_FIXTURE_DOC.exists()
    assert TEMPLATE_QA_GATE_DOC.exists()


def test_phase_source_result_head_and_tag_are_recorded() -> None:
    text = _text()
    assert "CID.LOCAL_MEDIA_AGENT.REAL.PREFLIGHT.MINIMAL.RUNTIME.CLI.REAL_FOLDER.DEMO.VISIBLE.REPORT.STATIC.FIXTURE.QA.GATE.V1" in text
    assert "CID.LOCAL_MEDIA_AGENT.REAL.PREFLIGHT.MINIMAL.RUNTIME.CLI.REAL_FOLDER.DEMO.VISIBLE.REPORT.STATIC.FIXTURE.V1" in text
    assert "LOCAL_MEDIA_AGENT_VISIBLE_REPORT_STATIC_FIXTURE_PASS_READY_FOR_STATIC_FIXTURE_QA_GATE" in text
    assert "457248f3f7da9ea0f7e77e29b5709380876201c6" in text
    assert "cid-dev-stable-local-media-agent-real-preflight-minimal-runtime-cli-real-folder-demo-visible-report-static-fixture-v1-20260620" in text


def test_files_under_qa_are_recorded() -> None:
    text = _text()
    assert "cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_fixture_v1.md" in text
    assert "cid_local_media_agent_real_preflight_minimal_runtime_cli_real_folder_demo_visible_report_static_template_qa_gate_v1.md" in text


def test_all_qa_checks_are_defined() -> None:
    text = _text()
    for token in [
        "Check 1 - Fixture identity is complete",
        "Check 2 - Visible report sections are present and ordered",
        "Check 3 - Local-only privacy remains visible",
        "Check 4 - Controlled demo input remains synthetic",
        "Check 5 - Scanner facts remain consistent",
        "Check 6 - Media tables remain producer-readable",
        "Check 7 - Human review and warning remain explicit",
        "Check 8 - Current outputs and roadmap are not over-claimed",
        "Check 9 - Fixture contains no local environment leaks",
        "Check 10 - Boundary remains closed",
    ]:
        assert token in text


def test_fixture_identity_is_gated() -> None:
    text = _text()
    for token in [
        "CID Local Media Agent - Internal Demo Visible Report",
        "local_media_agent_visible_report_static_fixture_v1",
        "producer_product_post_internal_review",
        "internal_demo_only",
        "local_only",
        "approved_synthetic_controlled_demo",
        "Generated by runtime: false",
        "Runtime generator available: false",
        "Real client media used: false",
    ]:
        assert token in text


def test_required_sections_are_gated() -> None:
    text = _text()
    for token in [
        "Executive Summary",
        "Local-Only Privacy Confirmation",
        "Controlled Demo Input Summary",
        "Scanner Result Summary",
        "Accepted Media",
        "Rejected Non-Media",
        "Human Review Required",
        "Warnings",
        "Created Output Artifacts",
        "Roadmap Modules Not Yet Generated",
        "Producer Interpretation",
        "Next Technical Actions",
    ]:
        assert token in text


def test_local_only_privacy_and_synthetic_input_are_gated() -> None:
    text = _text()
    for token in [
        "Privacy status: local_only_confirmed",
        "Original media left client system: false",
        "SaaS upload performed: false",
        "Network call performed: false",
        "Database write performed: false",
        "local user names are avoided",
        "machine names are avoided",
        "absolute system paths are avoided",
        "repository paths are avoided",
        "real client material is avoided",
        "Input mode: synthetic_controlled_demo_folder",
        "Input material type: synthetic_placeholders_only",
        "Input folder disclosure: redacted_for_visible_report",
        "Real shoot names disclosed: false",
        "Private project names disclosed: false",
    ]:
        assert token in text


def test_scanner_facts_and_media_tables_are_gated() -> None:
    text = _text()
    for token in [
        "Scanner status: completed_with_warnings",
        "Candidate media count: 5",
        "Accepted media count: 4",
        "Rejected non-media count: 3",
        "Human review required count: 1",
        "Warnings count: 1",
        "ffprobe preflight: skipped",
        "`.mov = 1`",
        "`.mp4 = 2`",
        "`.wav = 1`",
        "`.exe = 1`",
        "`.txt = 2`",
        "not synchronized clips, transcribed clips, subtitled clips, edited deliverables, or exported timelines",
    ]:
        assert token in text


def test_human_review_warning_outputs_and_roadmap_are_gated() -> None:
    text = _text()
    for token in [
        "Human review required: true",
        "Human review reason: unknown synthetic placeholder",
        "Warning count: 1",
        "Warning detail: unknown synthetic placeholder",
        "Warning severity: controlled_demo_warning",
        "`00_project/`",
        "`01_media_catalog/`",
        "`99_logs/`",
        "audio synchronization",
        "transcription",
        "subtitle outputs",
        "export outputs",
        "`02_audio_sync/`",
        "`03_transcription/`",
        "`04_subtitles/`",
        "`05_reports/`",
        "`06_exports/`",
    ]:
        assert token in text


def test_forbidden_local_environment_tokens_are_gated() -> None:
    text = _text()
    for token in [
        "`/mnt/`",
        "Windows drive paths",
        "UNC paths",
        "`DESKTOP-`",
        "`harliesound`",
        "`SERVICIOS_CINE`",
        "repository paths",
        "real shoot filenames",
        "private project titles",
    ]:
        assert token in text


def test_static_fixture_does_not_contain_local_environment_leaks() -> None:
    text = _text(STATIC_FIXTURE_DOC)
    forbidden = [
        "/mnt/",
        "DESKTOP-",
        "harliesound",
        "SERVICIOS_CINE",
        "\\\\wsl.localhost",
        "C:\\\\",
    ]
    for token in forbidden:
        assert token not in text


def test_boundary_decision_result_and_next_phase_are_recorded() -> None:
    text = _text()
    for token in [
        "runtime report generation",
        "scanner implementation changes",
        "real media scanning",
        "public demo use",
        "client-facing demo use",
        "ffprobe execution",
        "ffmpeg execution",
        "SaaS upload",
        "database writes",
        "network calls",
        "Docker or Alembic changes",
        "frontend/backend SaaS changes",
        "Stripe, AI Jobs, credits, or ledger changes",
        "controlled internal example of the visible report shape",
        "without claiming runtime generation, media synchronization, transcription, subtitling, translation, editing, or export automation",
        "LOCAL_MEDIA_AGENT_VISIBLE_REPORT_STATIC_FIXTURE_QA_GATE_PASS_READY_FOR_RUNTIME_REPORT_GENERATOR_CONTRACT",
        "CID.LOCAL_MEDIA_AGENT.REAL.PREFLIGHT.MINIMAL.RUNTIME.CLI.REAL_FOLDER.DEMO.VISIBLE.REPORT.RUNTIME.GENERATOR.CONTRACT.V1",
    ]:
        assert token in text
